actor User
User -> "~#createUser: Button" as createUserButton: click
createUserButton -> createUserController: loadView(FXMLLoader)
createUserController -> "~#username: TextField" as usernameField: getText()
createUserController -> SelectGameController: openView(User)
createUserController -> RestModel: createUser(User)
RestModel --> RestController: createUser(POST Http Request)
RestController -> UserModelService: createUser(User)
SelectGameController -> RouletteController: loadView(FXMLLoader)
RouletteController -> RouletteController: run()
RouletteController -> RestModel: updateUser(User)
RestModel --> RestController: updateUser(POST Http request)
